
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kuadrant.kuadrant.io
  resources:
  - kuadrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.kuadrant.io
  resources:
  - kuadrants/finalizers
  verbs:
  - update
- apiGroups:
  - kuadrant.kuadrant.io
  resources:
  - kuadrants/status
  verbs:
  - get
  - patch
  - update
