
resources:
  - ../default

patches:
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: dnsrecords.kuadrant.io
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: managedzones.kuadrant.io
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: dns-operator-controller-manager
        namespace: kuadrant-system
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: dns-operator-leader-election-role
        namespace: kuadrant-system
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: dns-operator-manager-role
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: dns-operator-leader-election-rolebinding
        namespace: kuadrant-system
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dns-operator-manager-rolebinding
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: dns-operator-controller-manager-metrics-service
        namespace: kuadrant-system
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dns-operator-controller-manager
        namespace: kuadrant-system
